from __future__ import annotations

import re
from dataclasses import dataclass, field

from assay.config import DEFAULT_GATE, GateThresholds

_VALID_MODES = ("chat", "completion")


@dataclass(frozen=True)
class Calib:
    dataset: str
    split: str
    num_samples: int
    max_seq_len: int


@dataclass(frozen=True)
class Eval:
    # Each accuracy task carries its FULLY-QUALIFIED lm-eval metric key, incl. any
    # filter suffix (e.g. gpqa reports both exact_match,flexible-extract and
    # exact_match,strict-match - naming the filter removes the ambiguity).
    accuracy_tasks: tuple[tuple[str, str], ...]
    perplexity: tuple[str, str] | None      # (task, metric) or None to skip the ppl gate
    mode: str                                # "chat" | "completion"
    gen_kwargs: dict | None                  # sampling for generative tasks; global to the run
    system_prompt: str | None                # None => no system prompt (R1 requires this)
    prompt_prefix: str | None                # forced assistant-turn prefix, e.g. "<think>\n"
    # Targeted multi-sampling: task -> sample count K (avg@K). Empty => every task
    # single-sampled (today's behavior). Spend K only where stderr is large: aime
    # (n=30, ~9pt stderr) needs it; minerva/gpqa are already tight.
    repeats: dict[str, int] = field(default_factory=dict)


@dataclass(frozen=True)
class Recipe:
    slug: str
    base_model: str
    quant_scheme: str
    calib: Calib
    eval: Eval
    gate: GateThresholds | None              # None => DEFAULT_GATE
    tags: tuple[str, ...]
    # SPDX id for the card's front matter. A quantization is a derivative work, so this
    # must track the BASE MODEL's license - it is not a constant. It was hardcoded to
    # "apache-2.0" in publish.py, which silently misdeclared the R1 card (upstream
    # DeepSeek-R1-Distill-Qwen-7B is MIT). Defaulted empty and REQUIRED by
    # validate_recipe, which load_config runs before any GPU spend: a new recipe cannot
    # publish under an unstated license, and cannot inherit a wrong one by omission.
    license: str = ""
    # Base-model identity pins (F-015/F-027), generated by scripts/pin_base_files.py.
    # base_revision is the upstream COMMIT sha the pins were taken at - never a branch
    # or tag, which is exactly the moving target the pin removes. base_files maps
    # repo-relative file -> sha256 covering config.json, the safetensors index,
    # tokenizer_config.json (it carries the chat template driving calibration), and
    # the weight shards. verify.py checks the staged volume against this map in-pod,
    # BEFORE quantize: a mis-staged or partially re-staged volume would otherwise
    # publish the wrong model under a correct-looking card, still marked pristine.
    # The trust anchor is deliberately the reviewed GIT recipe, not a staging-time
    # manifest on the volume - a manifest anchors trust to the same mutable volume
    # being validated.
    base_revision: str = ""
    base_files: dict[str, str] = field(default_factory=dict)

    @property
    def accuracy_task_names(self) -> tuple[str, ...]:
        return tuple(task for task, _ in self.eval.accuracy_tasks)

    @property
    def perplexity_task_name(self) -> str | None:
        return None if self.eval.perplexity is None else self.eval.perplexity[0]

    @property
    def gate_or_default(self) -> GateThresholds:
        return self.gate or DEFAULT_GATE


# Format/framework tags per HF convention; the supported-architecture story lives in
# the generated Hardware Requirements card section, not a GPU-name laundry list.
_NVFP4A16_TAGS = (
    "text-generation", "nvfp4", "nvfp4a16", "fp4", "e2m1", "weight-only",
    "compressed-tensors", "vllm", "quantized", "llm-compressor",
)

RECIPES: dict[str, Recipe] = {
    "qwen2_5_7b_instruct": Recipe(
        slug="qwen2_5_7b_instruct",
        base_model="Qwen/Qwen2.5-7B-Instruct",
        quant_scheme="NVFP4A16",
        calib=Calib("HuggingFaceH4/ultrachat_200k", "train_sft", 512, 2048),
        eval=Eval(
            accuracy_tasks=(
                # flexible-extract, NOT strict-match: in chat mode the model answers
                # conversationally rather than in gsm8k's "#### <n>" completion format,
                # so strict-match under-extracts (measured on metal: baseline collapsed
                # to ~0.18 vs the true ~0.80). flexible-extract pulls the final number
                # out of chat-formatted output. The gate is apples-to-apples either way,
                # but the absolute score must reflect real chat-mode capability.
                ("gsm8k", "exact_match,flexible-extract"),
                ("arc_challenge", "acc,none"),
                ("hellaswag", "acc,none"),
                ("winogrande", "acc,none"),
                ("mmlu", "acc,none"),
            ),
            perplexity=("wikitext", "word_perplexity"),
            mode="chat",              # the re-cert upgrade: eval as the model is used
            gen_kwargs=None,
            system_prompt=None,
            prompt_prefix=None,
        ),
        gate=None,
        tags=_NVFP4A16_TAGS + ("qwen2", "qwen2.5", "conversational"),
        license="apache-2.0",   # matches Qwen/Qwen2.5-7B-Instruct upstream
        # scripts/pin_base_files.py, fetched 2026-07-26 (F-015/F-027; tokenizer +
        # generation-config surface added by F-031, same revision).
        base_revision="a09a35458c702b33eeacc393d103063234e8bc28",
        base_files={
            "config.json": "7463bb0ea78315365e6c6b74de4e73bbcc8359dfb0c5a737584e077d42c0b03c",
            "generation_config.json": "3a8f9087e486054c8a4a08dae2e5a3ba62e23da212b5b8c08bc42cb983c3459f",
            "merges.txt": "599bab54075088774b1733fde865d5bd747cbcc7a547c5bc12610e874e26f5e3",
            "model-00001-of-00004.safetensors": "a1333e6293854747c481288ea83b348226af178dd565c49b6f9495ba1966aba7",
            "model-00002-of-00004.safetensors": "f5d25a2772cb825164a2a2c0fb6d51a87e282abf21e4dd75bc5cfb3cd0ea6185",
            "model-00003-of-00004.safetensors": "8efdec4c1bc12317ae1a38dc42b595ce777738a64deea3fcb8a0a91381bcdfd5",
            "model-00004-of-00004.safetensors": "1a72d403cdf0c1ec3cb7f289f17b394a01e64394c2e9b3c0f94dbce3faf879bd",
            "model.safetensors.index.json": "624bf7c47cd12468fdc16e38a47cf4f19e0415b859a223ba3c027eed2f0e1028",
            "tokenizer.json": "c0382117ea329cdf097041132f6d735924b697924d6f6fc3945713e96ce87539",
            "tokenizer_config.json": "5b5d4f65d0acd3b2d56a35b56d374a36cbc1c8fa5cf3b3febbbfabf22f359583",
            "vocab.json": "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910",
        },
    ),
    "r1_distill_qwen_7b": Recipe(
        slug="r1_distill_qwen_7b",
        base_model="deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        quant_scheme="NVFP4A16",
        calib=Calib("HuggingFaceH4/ultrachat_200k", "train_sft", 512, 2048),
        eval=Eval(
            accuracy_tasks=(
                ("aime24_avg", "exact_match,avg"),
                ("aime25_avg", "exact_match,avg"),
                # math_verify (from lm-eval[math]) not exact_match: R1 emits
                # <think>...\boxed{} answers that the Minerva-prompt exact_match
                # extractor misses (scored 0.0000 both sides on metal); math_verify
                # is a robust symbolic verifier and read 0.84 in the same run.
                ("minerva_math500", "math_verify,none"),
                ("gpqa_diamond_cot_zeroshot", "exact_match,flexible-extract"),
            ),
            perplexity=("wikitext", "word_perplexity"),
            mode="chat",
            # DeepSeek card: temperature 0.6, top_p 0.95, no system prompt, and the
            # response must begin with "<think>\n". do_sample=True is required or the
            # task-YAML greedy default stays in effect. max_gen_toks matches aime24.yaml.
            gen_kwargs={"temperature": 0.6, "top_p": 0.95, "do_sample": True, "max_gen_toks": 32768},
            system_prompt=None,
            # prompt_prefix stays None ON PURPOSE. This checkpoint's own chat_template
            # ends with `{% if add_generation_prompt %}...<think>\n{% endif %}`, and
            # lm-eval sets add_generation_prompt=True in chat mode - so "<think>\n" is
            # ALREADY forced onto every generation prompt. Setting a prefix here would
            # DOUBLE it. The prompt_prefix mechanism remains (validated, unwired) for a
            # future checkpoint whose template does NOT auto-append. (Verified against
            # the live deepseek-ai/DeepSeek-R1-Distill-Qwen-7B chat_template.)
            prompt_prefix=None,
            # avg@16 on the two AIME sets. AIME is n=30, temperature 0.6, single-sample
            # combined stderr ~0.18 (~11-question gate threshold) - "nearly decorative".
            # Averaging K=16 samples per question shrinks the sampling-noise term ~1/sqrt(K)
            # toward the between-question floor, giving the significance gate real teeth.
            # WIRED via the assay-owned aime24_avg/aime25_avg tasks (lm_eval_tasks/) +
            # evaluate.py repeats injection; stock lm-eval 0.4.12 take_first cannot avg@K.
            # K applies to AIME only: minerva (n=500) and gpqa (n=198) are already
            # well-powered by their large n.
            repeats={"aime24_avg": 16, "aime25_avg": 16},
        ),
        # Significance-gated, not point-gated: tiny generative sets (aime n=30) make
        # max_single_drop_pts structurally wrong (one question = 3.3pt > 2pt). k=2 is
        # the standard "beyond the error bars" bar. ppl stays the strict weight-
        # preservation backstop (ratio-gated, low variance - R1 quant was +0.47%).
        gate=GateThresholds(
            min_mean_retention=None,
            max_single_drop_pts=None,
            max_ppl_increase=0.03,
            k_stderr=2.0,
        ),
        tags=_NVFP4A16_TAGS + ("deepseek", "deepseek-r1", "reasoning", "conversational"),
        # MIT, NOT apache-2.0: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B declares MIT
        # upstream (verified against the Hub 2026-07-26). The old hardcoded apache-2.0
        # misdeclared this checkpoint's license on the live card.
        license="mit",
        # scripts/pin_base_files.py, fetched 2026-07-26 (F-015/F-027; tokenizer +
        # generation-config surface added by F-031, same revision - this repo has no
        # top-level vocab.json/merges.txt, tokenizer.json carries both). The six-digit
        # shard suffix (000002) is DeepSeek's own upstream naming, not a typo.
        base_revision="916b56a44061fd5cd7d6a8fb632557ed4f724f60",
        base_files={
            "config.json": "8290d3c1e385e2616572eb6926f7e2745f901d1c13da95970326a8a73f6c379c",
            "generation_config.json": "72cbec1015da9ed03ad025483005cbf6481403abf947adfd54e504d1a66a2126",
            "model-00001-of-000002.safetensors": "8b27be8d43b81d0cd19b3113ef88caf1a61c2fc602de77e3cce97aedcec184b4",
            "model-00002-of-000002.safetensors": "1780a9502f56f592cb4d6262c8c76ca8ad36a86b0257e052c672d87f49707e80",
            "model.safetensors.index.json": "788266ec033788abcf34b2cb8fe156ce300ae05d94d3d54c60f2ecffd8927a1a",
            "tokenizer.json": "88145e3c3249adc2546ede277e9819d6e405e19072456e4b521cbc724bd60773",
            "tokenizer_config.json": "8ac8c85fb242563c2260baec0909debd69d718af6a0b3d90e6cab62b4d341cd5",
        },
    ),
    # --- TEMPLATE: copy this block, rename the slug, edit the fields. ---
    # Adding a model = adding one Recipe here (reviewable diff). Keep metric keys
    # FULLY-QUALIFIED (include the lm-eval filter suffix). Set mode="chat" for
    # instruct/reasoning models. Leave gate=None to inherit DEFAULT_GATE.
    "template_example": Recipe(
        slug="template_example",
        base_model="org/YourModel-Instruct",
        quant_scheme="NVFP4A16",
        calib=Calib("HuggingFaceH4/ultrachat_200k", "train_sft", 512, 2048),
        eval=Eval(
            accuracy_tasks=(("mmlu", "acc,none"),),
            perplexity=("wikitext", "word_perplexity"),
            mode="chat",
            gen_kwargs=None,
            system_prompt=None,
            prompt_prefix=None,
        ),
        gate=None,
        tags=_NVFP4A16_TAGS,
        # REQUIRED: set this to the BASE MODEL's license, not a copied default.
        license="apache-2.0",
    ),
}


def get_recipe(slug: str) -> Recipe:
    try:
        return RECIPES[slug]
    except KeyError:
        raise KeyError(
            f"unknown recipe {slug!r}; valid slugs: {', '.join(sorted(RECIPES))}"
        ) from None


def validate_recipe(recipe: Recipe) -> None:
    """Cheap structural validation - catch a malformed recipe in milliseconds,
    before any paid GPU work. Does NOT hit the network (task existence is proven
    on metal)."""
    if not recipe.base_model:
        raise ValueError(
            f"recipe {recipe.slug!r}: base_model is required (got empty/unset - check "
            "ASSAY_BASE_MODEL if this was an env override)")
    if not recipe.quant_scheme:
        raise ValueError(
            f"recipe {recipe.slug!r}: quant_scheme is required (got empty/unset - check "
            "ASSAY_QUANT_SCHEME if this was an env override)")
    if not recipe.calib.dataset:
        raise ValueError(
            f"recipe {recipe.slug!r}: calib.dataset is required (got empty/unset - check "
            "ASSAY_CALIB_DATASET if this was an env override)")
    if not recipe.calib.split:
        raise ValueError(
            f"recipe {recipe.slug!r}: calib.split is required (got empty/unset - check "
            "ASSAY_CALIB_SPLIT if this was an env override)")
    ev = recipe.eval
    if not ev.accuracy_tasks:
        raise ValueError(f"recipe {recipe.slug!r}: needs at least one accuracy task")
    if ev.mode not in _VALID_MODES:
        raise ValueError(f"recipe {recipe.slug!r}: mode must be one of {_VALID_MODES}, got {ev.mode!r}")
    if ev.prompt_prefix is not None and ev.mode != "chat":
        raise ValueError(
            f"recipe {recipe.slug!r}: prompt_prefix requires mode='chat' (it is a "
            "forced assistant-turn prefix rendered through the chat template)")
    for task, metric in ev.accuracy_tasks:
        if not task or not metric:
            raise ValueError(f"recipe {recipe.slug!r}: empty task/metric in accuracy_tasks: {(task, metric)!r}")
        if "," not in metric:
            raise ValueError(
                f"recipe {recipe.slug!r}: accuracy metric key {metric!r} for task {task!r} "
                "must be fully qualified with its lm-eval filter suffix (e.g. 'acc,none', "
                "'exact_match,strict-match')")
    for rtask, rk in ev.repeats.items():
        if rtask not in recipe.accuracy_task_names:
            raise ValueError(
                f"recipe {recipe.slug!r}: repeats key {rtask!r} is not one of the "
                f"recipe's accuracy tasks {recipe.accuracy_task_names}")
        if not isinstance(rk, int) or rk < 1:
            raise ValueError(
                f"recipe {recipe.slug!r}: repeats[{rtask!r}] must be an int >= 1, got {rk!r}")
    if ev.perplexity is not None:
        ptask, pmetric = ev.perplexity
        if not ptask or not pmetric:
            raise ValueError(f"recipe {recipe.slug!r}: perplexity must be (task, metric) or None")
    if not recipe.tags:
        raise ValueError(f"recipe {recipe.slug!r}: at least one tag is required for the model card")
    # A criteria-free gate is a false-certification hazard: an EXPLICIT all-None
    # GateThresholds is truthy, so gate_or_default does NOT substitute DEFAULT_GATE,
    # and evaluate_gate then fires zero criteria and PASSES any quantization -> the
    # checkpoint publishes and is DOI-minted on no evidence. gate=None is the supported
    # "use DEFAULT_GATE" path; a criteria-free explicit gate must be rejected here.
    if recipe.gate is not None and not any((
            recipe.gate.min_mean_retention is not None,
            recipe.gate.max_single_drop_pts is not None,
            recipe.gate.max_ppl_increase is not None,
            recipe.gate.k_stderr is not None)):
        raise ValueError(
            f"recipe {recipe.slug!r}: gate has no active criteria (all thresholds are "
            "None). A criteria-free gate would PASS any quantization and publish a false "
            "certification. Set at least one threshold, or use gate=None for DEFAULT_GATE.")
    # Significance support matrix (BITE 2, D7): the paired test rests on the
    # pooled-mean identity, which holds only for mean-aggregated scalar per-item
    # metrics. A perplexity-family metric under a k_stderr gate would pass config and
    # then fail AFTER a paid eval (tuple per-item values, no mean identity), so it is
    # refused here at $0. This list names known NON-mean aggregations, not allowed
    # metrics - a new mean-aggregated metric needs no edit here; the authoritative
    # runtime control is the per-side reconciliation assert in pairing.collect_items.
    if recipe.gate is not None and recipe.gate.k_stderr is not None:
        non_mean = ("word_perplexity", "byte_perplexity", "bits_per_byte")
        for task, metric in recipe.eval.accuracy_tasks:
            if metric.split(",", 1)[0] in non_mean:
                raise ValueError(
                    f"recipe {recipe.slug!r}: accuracy task {task!r} uses {metric!r} "
                    "under a k_stderr gate, but the paired significance test requires "
                    "a mean-aggregated per-item metric (perplexity aggregates as "
                    "weighted perplexity and its per-item values are tuples). Put it "
                    "in eval.perplexity, where the ratio hard bar applies.")
    # Base-model identity pins (F-015/F-027): both halves or neither. The sha map is
    # only meaningful AT the revision it was generated from, and a pinned revision
    # with no file map verifies nothing.
    if bool(recipe.base_files) != bool(recipe.base_revision):
        raise ValueError(
            f"recipe {recipe.slug!r}: base_revision and base_files must be set together "
            "- the sha256 map is only meaningful at the commit it was generated from. "
            "Regenerate both with scripts/pin_base_files.py.")
    if recipe.base_revision and not re.fullmatch(r"[0-9a-f]{40}", recipe.base_revision):
        raise ValueError(
            f"recipe {recipe.slug!r}: base_revision {recipe.base_revision!r} must be the "
            "40-hex upstream commit sha - a branch or tag name is a moving target, which "
            "is exactly what the pin exists to remove (scripts/pin_base_files.py emits it).")
    for pin_path, digest in recipe.base_files.items():
        if not pin_path or pin_path.startswith("/") or ".." in pin_path:
            raise ValueError(
                f"recipe {recipe.slug!r}: base_files key {pin_path!r} must be a relative "
                "path inside the base model repo (no leading '/', no '..').")
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise ValueError(
                f"recipe {recipe.slug!r}: base_files[{pin_path!r}] must be a 64-hex "
                f"sha256, got {digest!r}. Regenerate with scripts/pin_base_files.py.")
    # Checked LAST so the more specific structural errors above keep reporting first.
    # A quantization is a derivative work: publishing it under a license the base model
    # did not grant is a legal misstatement on the card, not a cosmetic one. There is
    # deliberately no default to inherit - the old hardcoded "apache-2.0" is exactly how
    # the R1 card (base model: MIT) came to declare the wrong license.
    if not recipe.license:
        raise ValueError(
            f"recipe {recipe.slug!r}: license is required - set it to the SPDX id of the "
            f"BASE MODEL's license (check {recipe.base_model or '<base_model>'} on the Hub). "
            "It is published in the model card's front matter, so it must not be guessed "
            "or copied from another recipe.")
