"""In-pod, OFFLINE verification that the staged weights are the model the recipe
certifies (F-015).

ASSAY_WEIGHTS_PATH used to be trusted raw: a mis-staged volume quantizes and
publishes the WRONG model under a correct-looking card, still marked pristine, so it
can mint a real DOI cert. The trust anchor is the reviewed GIT recipe's identity pins
(recipes.Recipe.base_revision / base_files, generated by scripts/pin_base_files.py) -
deliberately not a staging-time manifest, which would anchor trust to the same
mutable volume being validated. No network: the pins travel in the image.

Two passes, called from job.main() around the GPU preflight:
- verify_weights_small: config.json / safetensors index / the full tokenizer
  surface (tokenizer.json + tokenizer_config.json + vocab/merges where present) /
  generation_config.json (F-031), every tier, fast. config.json alone is NOT an
  acceptable floor, but it and friends catch the cheap staging mistakes before
  anything expensive happens.
- verify_weights_shards: full sha256 over the weight shards (~1-3 min against a
  multi-hour burn), gated on `pristine` - the exact set of runs that can mint a real
  cert. This is what catches the partial-re-stage chimera: the two live base models
  are architecturally identical, so right-config-beside-wrong-shards LOADS cleanly,
  both eval sides run on it, and the purely-relative gate has no absolute floor to
  object - a certified card over garbage.

ASSAY_BASE_MODEL present skips both passes, LOUDLY. The documented 2 AM escape hatch
swaps recipe.base_model, so the pins describe a model the operator deliberately did
not stage; hard-failing there would brick the escape hatch. Safe by construction:
that var breaks `pristine` (config._NONPRISTINE_VARS), so the invariant holds stated
positively - NO RUN THAT CAN PUBLISH A REAL CERT RUNS ON UNVERIFIED WEIGHTS
(pinned by tests/test_verify.py::test_base_model_override_breaks_pristine).

Every failure is a HARD SystemExit, never a demotion to dry-run: a demoted run burns
hours of paid GPU producing plausible artifacts about the wrong model, and a dry run
still builds a card. Salvaging plumbing value is what the smoke/dev tiers are for.
"""
from __future__ import annotations

import hashlib
import os
import time
from collections.abc import Mapping

from assay.config import RunConfig


def sha256_file(path: str, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def _is_shard(name: str) -> bool:
    return name.endswith(".safetensors")


def _skipped_for_override(env: Mapping[str, str], which: str) -> bool:
    if "ASSAY_BASE_MODEL" not in env:
        return False
    print(f"[verify] {which} pass SKIPPED: ASSAY_BASE_MODEL overrides the recipe's "
          "base model, so the recipe's identity pins describe a model this run "
          "deliberately does not stage. Safe: that override forces dry-run, so this "
          "run cannot mint a real cert.", flush=True)
    return True


def _fail(msg: str) -> None:
    raise SystemExit(f"FATAL: {msg}")


def _require_pins(runcfg: RunConfig) -> None:
    recipe = runcfg.recipe
    if not recipe.base_files:
        _fail(
            f"recipe {recipe.slug!r} has no base-model identity pins, so the staged "
            f"weights at {runcfg.weights_path!r} cannot be verified against "
            f"{recipe.base_model}. On the dev box run: uv run python "
            f"scripts/pin_base_files.py {recipe.slug}  and paste the emitted "
            "base_revision/base_files into the recipe. For a deliberate one-off on a "
            "different model, set ASSAY_BASE_MODEL (forces dry-run).")


def _check_files(runcfg: RunConfig, names: list[str]) -> None:
    recipe = runcfg.recipe
    for name in names:
        path = os.path.join(runcfg.weights_path, name)
        remedy = (
            f"Re-stage {recipe.base_model} @ {recipe.base_revision} onto the volume - "
            "a PARTIAL re-stage can leave a mix of two models that still loads "
            "cleanly. If a different model is intended, set ASSAY_BASE_MODEL "
            "(forces dry-run) instead of editing the volume.")
        if not os.path.exists(path):
            _fail(
                f"{name} is pinned for recipe {recipe.slug!r} but missing from the "
                f"staged weights at {runcfg.weights_path!r} - the volume is mis-staged "
                f"or partially staged. {remedy}")
        actual = sha256_file(path)
        expected = recipe.base_files[name]
        if actual != expected:
            _fail(
                f"{name} at {runcfg.weights_path!r} does not match recipe "
                f"{recipe.slug!r}'s pin for {recipe.base_model} @ "
                f"{recipe.base_revision}: expected sha256 {expected[:16]}.., staged "
                f"file is {actual[:16]}.. - the staged volume does not hold the "
                f"certified base model. {remedy}")


def verify_weights_small(runcfg: RunConfig, env: Mapping[str, str]) -> None:
    """Sub-second identity check of the small pinned files; EVERY tier - wrong
    weights on a dev run are still hours of wrong-model burn."""
    if _skipped_for_override(env, "weights identity (small files)"):
        return
    _require_pins(runcfg)
    recipe = runcfg.recipe
    names = [n for n in sorted(recipe.base_files) if not _is_shard(n)]
    _check_files(runcfg, names)
    print(f"[verify] weights identity OK: {len(names)} identity files match recipe "
          f"{recipe.slug} pins ({recipe.base_model} @ {recipe.base_revision[:12]})",
          flush=True)


def verify_weights_shards(runcfg: RunConfig, env: Mapping[str, str]) -> None:
    """Full sha256 pass over the pinned weight shards. Gated on `pristine` - exactly
    the runs that can mint a real cert - because it costs minutes of hashing; the
    small pass already ran on every tier."""
    if _skipped_for_override(env, "weights shard-hash"):
        return
    if not runcfg.pristine:
        print("[verify] shard-hash pass skipped: run is not pristine so it cannot "
              "mint a real cert; small-file identity was already verified.",
              flush=True)
        return
    _require_pins(runcfg)
    recipe = runcfg.recipe
    names = [n for n in sorted(recipe.base_files) if _is_shard(n)]
    start = time.monotonic()
    _check_files(runcfg, names)
    print(f"[verify] weights shard hashes OK: {len(names)} shards match recipe "
          f"{recipe.slug} pins in {time.monotonic() - start:.0f}s", flush=True)
